# Generated by Django 3.0.8 on 2023-04-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200920_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullorder',
            old_name='zipcode',
            new_name='eircode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='eircode',
        ),
    ]
