version: 0.2

version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
phases:
  install:
    runtime-versions:
      python: 3.
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      #- python manage.py test
      - echo Collecting static files...
      - python manage.py collectstatic --noinput
artifacts:
  files:
    - '**/*'
